print("Welcome to the Band Name Generator")
city = input("what city did you grow up in?\n")
print(city)
pet_name = input("What is your pet's name?\n")
print(pet_name)
print("Your band name could be "+city+" "+pet_name)